# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Feb  4 02:25:29 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 915)
        icon = QtGui.QIcon.fromTheme("fox")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 0, 1, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 0, 1, 5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_21.setCheckable(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_3.addWidget(self.pushButton_21, 2, 7, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 1, 5, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 1, 6, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 1, 7, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 1, 8, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 1, 9, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 1, 10, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 4, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_3.addWidget(self.pushButton_13, 1, 11, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_3.addWidget(self.pushButton_15, 2, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_3.addWidget(self.pushButton_16, 2, 2, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_3.addWidget(self.pushButton_17, 2, 3, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_19.setCheckable(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_3.addWidget(self.pushButton_19, 2, 5, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_18.setCheckable(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_3.addWidget(self.pushButton_18, 2, 4, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_3.addWidget(self.pushButton_20, 2, 6, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_22.setCheckable(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_3.addWidget(self.pushButton_22, 2, 8, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 3, 4, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_23.setCheckable(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_3.addWidget(self.pushButton_23, 2, 9, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_3.addWidget(self.pushButton_24, 2, 10, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_25.setCheckable(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_3.addWidget(self.pushButton_25, 2, 11, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 5)
        self.pushButton_49 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_49.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout.addWidget(self.pushButton_49, 5, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 2, 1, 1)
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.exitBtn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.exitBtn.setObjectName("exitBtn")
        self.gridLayout.addWidget(self.exitBtn, 5, 4, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout_5.addWidget(self.pushButton_43, 2, 6, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_5.addWidget(self.pushButton_40, 2, 3, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_5.addWidget(self.pushButton_44, 2, 7, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_5.addWidget(self.pushButton_38, 2, 1, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_39.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_5.addWidget(self.pushButton_39, 2, 2, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout_5.addWidget(self.pushButton_41, 2, 4, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_5.addWidget(self.pushButton_42, 2, 5, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_45.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout_5.addWidget(self.pushButton_45, 2, 8, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_46.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout_5.addWidget(self.pushButton_46, 2, 9, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_47.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout_5.addWidget(self.pushButton_47, 2, 10, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 0, 5, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_48.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout_5.addWidget(self.pushButton_48, 2, 11, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_28.setCheckable(False)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_5.addWidget(self.pushButton_28, 1, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_5.addWidget(self.pushButton_14, 1, 1, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_5.addWidget(self.pushButton_26, 1, 2, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_5.addWidget(self.pushButton_27, 1, 3, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_5.addWidget(self.pushButton_29, 1, 4, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_5.addWidget(self.pushButton_30, 1, 5, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_5.addWidget(self.pushButton_33, 1, 8, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_5.addWidget(self.pushButton_31, 1, 6, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_5.addWidget(self.pushButton_37, 2, 0, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_5.addWidget(self.pushButton_32, 1, 7, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_5.addWidget(self.pushButton_34, 1, 9, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_5.addWidget(self.pushButton_35, 1, 10, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_5.addWidget(self.pushButton_36, 1, 11, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 3, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 3, 0, 1, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 20))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.exitAct = QtWidgets.QAction(MainWindow)
        self.exitAct.setObjectName("exitAct")
        self.menu.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.exitAct)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.exitBtn.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chords to Gamma"))
        self.label.setText(_translate("MainWindow", "Гамма"))
        self.pushButton_4.setText(_translate("MainWindow", "B"))
        self.pushButton_3.setText(_translate("MainWindow", "A#"))
        self.pushButton.setText(_translate("MainWindow", "A"))
        self.pushButton_2.setText(_translate("MainWindow", "Am"))
        self.pushButton_21.setText(_translate("MainWindow", "Em"))
        self.pushButton_5.setText(_translate("MainWindow", "C"))
        self.pushButton_6.setText(_translate("MainWindow", "C#"))
        self.pushButton_7.setText(_translate("MainWindow", "D"))
        self.pushButton_8.setText(_translate("MainWindow", "D#"))
        self.pushButton_9.setText(_translate("MainWindow", "E"))
        self.pushButton_10.setText(_translate("MainWindow", "F"))
        self.pushButton_11.setText(_translate("MainWindow", "F#"))
        self.pushButton_12.setText(_translate("MainWindow", "G"))
        self.pushButton_13.setText(_translate("MainWindow", "G#"))
        self.pushButton_15.setText(_translate("MainWindow", "A#m"))
        self.pushButton_16.setText(_translate("MainWindow", "Bm"))
        self.pushButton_17.setText(_translate("MainWindow", "Cm"))
        self.pushButton_19.setText(_translate("MainWindow", "Dm"))
        self.pushButton_18.setText(_translate("MainWindow", "C#m"))
        self.pushButton_20.setText(_translate("MainWindow", "D#m"))
        self.pushButton_22.setText(_translate("MainWindow", "Fm"))
        self.pushButton_23.setText(_translate("MainWindow", "F#m"))
        self.pushButton_24.setText(_translate("MainWindow", "Gm"))
        self.pushButton_25.setText(_translate("MainWindow", "G#m"))
        self.pushButton_49.setText(_translate("MainWindow", "Заново"))
        self.exitBtn.setText(_translate("MainWindow", "Выход"))
        self.pushButton_43.setText(_translate("MainWindow", "D#m"))
        self.pushButton_40.setText(_translate("MainWindow", "Cm"))
        self.pushButton_44.setText(_translate("MainWindow", "Em"))
        self.pushButton_38.setText(_translate("MainWindow", "A#m"))
        self.pushButton_39.setText(_translate("MainWindow", "Bm"))
        self.pushButton_41.setText(_translate("MainWindow", "C#m"))
        self.pushButton_42.setText(_translate("MainWindow", "Dm"))
        self.pushButton_45.setText(_translate("MainWindow", "Fm"))
        self.pushButton_46.setText(_translate("MainWindow", "F#m"))
        self.pushButton_47.setText(_translate("MainWindow", "Gm"))
        self.pushButton_48.setText(_translate("MainWindow", "G#m"))
        self.pushButton_28.setText(_translate("MainWindow", "A"))
        self.pushButton_14.setText(_translate("MainWindow", "A#"))
        self.pushButton_26.setText(_translate("MainWindow", "B"))
        self.pushButton_27.setText(_translate("MainWindow", "C"))
        self.pushButton_29.setText(_translate("MainWindow", "C#"))
        self.pushButton_30.setText(_translate("MainWindow", "D"))
        self.pushButton_33.setText(_translate("MainWindow", "F"))
        self.pushButton_31.setText(_translate("MainWindow", "D#"))
        self.pushButton_37.setText(_translate("MainWindow", "Am"))
        self.pushButton_32.setText(_translate("MainWindow", "E"))
        self.pushButton_34.setText(_translate("MainWindow", "F#"))
        self.pushButton_35.setText(_translate("MainWindow", "G"))
        self.pushButton_36.setText(_translate("MainWindow", "G#"))
        self.menu.setTitle(_translate("MainWindow", "Справка"))
        self.menu_2.setTitle(_translate("MainWindow", "Файл"))
        self.action.setText(_translate("MainWindow", "О программе ?"))
        self.action_2.setText(_translate("MainWindow", "Открыть"))
        self.action_3.setText(_translate("MainWindow", "Открыть недавние"))
        self.exitAct.setText(_translate("MainWindow", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

